export const BASE_URL = import.meta.env.VITE_APP_BASE_URL

export const SIGNUP_API = "/auth/register"
export const LOGIN_API = "/auth/login"
export const CHANGE_PASSWORD_API = "/auth/changePassword"
export const UPDATE_PROFILE_API= "profile/updateProfile"
export const UPDATE_USERNAME_API = "profile/updateUsername"
export const GET_SINGLE_USER_API = "profile/getSingleUser"
export const PRODUCT_URL_API = "/products"
export const GET_SINGLE_PRODUCT_API = "/products"
export const GET_REVIEW_API = "/review"
export const ADD_TO_CART_API = "/cart"
export const CREATE_ORDER_API = "/order"
export const GET_ORDER_API = "/order"
export const GET_SINGLE_ORDER_API = "/order"
export const DELETE_ORDER_API = "/order"